workspace = { members = ["lib/application", "lib/domain", "lib/framework"] }
[package]
name = "sandwich-recipes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
